services:
  bof-app:
    container_name: bof-app
    build:
      context: .
    ports:
      - 7500:80
    volumes:
      - ./:/var/www
    command: >
      sh -c "chown -R www-data:www-data /var/www/storage/ &&
             chown -R www-data:www-data /var/www/bootstrap/cache/ &&
             chmod -R 775 /var/www/storage/ &&
             chmod -R 775 /var/www/bootstrap/cache/ &&
             composer install --no-interaction --prefer-dist &&
             composer dump-autoload --optimize &&
             su -s /bin/sh -c 'php artisan optimize' www-data &&
             php artisan migrate --force &&
             php artisan optimize:clear &&
             php artisan config:clear &&
             service nginx start &&
             php-fpm"
    networks:
      - bof-network

  bof-db:
    container_name: bof-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bof-db
    command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
    volumes:
      - bof-db-data:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3308:3306"
    networks:
      - bof-network

networks:
  bof-network:
    driver: bridge

volumes:
  bof-db-data:
    name: bof-db-data